# Generated by Django 2.2.4 on 2019-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alice_public_key', models.CharField(editable=False, max_length=40, verbose_name='Alice Public Key')),
                ('bob_public_key', models.CharField(editable=False, max_length=40, verbose_name='Bob Public Key')),
                ('alice_private_key', models.CharField(editable=False, max_length=40, verbose_name='Alice Private Key')),
                ('bob_private_key', models.CharField(editable=False, max_length=40, verbose_name='Bob Private Key')),
            ],
            options={
                'verbose_name': 'User secret',
                'verbose_name_plural': 'Users secret',
            },
        ),
    ]
