# Generated by Django 2.2.4 on 2019-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuwill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNextKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bob_email_address', models.EmailField(editable=False, max_length=254, verbose_name='Bob Email Address')),
                ('bob_public_address', models.CharField(editable=False, max_length=40, verbose_name='Bob Public Address')),
                ('ipfs_address', models.TextField(verbose_name='IPFS Hash')),
            ],
            options={
                'verbose_name': "User's next of kin",
                'verbose_name_plural': "User's next of kin",
            },
        ),
    ]
