# Generated by Django 2.2.4 on 2019-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuwill', '0002_usernextkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecret',
            name='label',
            field=models.CharField(default='hello', max_length=10, verbose_name='Policy Label to identify'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersecret',
            name='policy_encrypting_key',
            field=models.CharField(default='hello', max_length=100, verbose_name='Alice policy Privacy encryption key'),
            preserve_default=False,
        ),
    ]
