# Generated by Django 2.2.4 on 2019-08-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuwill', '0003_auto_20190803_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecret',
            name='capsule',
            field=models.TextField(default='hello', verbose_name='Capsule/MessageKit'),
            preserve_default=False,
        ),
    ]
