# Generated by Django 2.2.4 on 2019-08-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nuwill', '0004_usersecret_capsule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecret',
            name='alice_private_key',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='alice_public_key',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='bob_private_key',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='bob_public_key',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='capsule',
        ),
        migrations.AddField(
            model_name='usernextkin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersecret',
            name='message_kit',
            field=models.TextField(default=1, verbose_name='MessageKit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersecret',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
