# Generated by Django 2.2.4 on 2019-08-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuwill', '0006_auto_20190803_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernextkin',
            name='ipfs_address',
            field=models.TextField(blank=True, null=True, verbose_name='IPFS Hash'),
        ),
    ]
