# Generated by Django 2.2.4 on 2019-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuwill', '0007_auto_20190803_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecret',
            name='alice_verifying_key',
            field=models.CharField(default=1, max_length=40, verbose_name='Alice verifying key'),
            preserve_default=False,
        ),
    ]
